#ifndef COMMON_TYPES_H
#define COMMON_TYPES_H

typedef enum {
  PPU_2C02 = 0,
  PPU_2C03 = 1,
  PPU_2C04A = 2,
  PPU_2C04B = 3,
  PPU_2C04C = 4,
  PPU_2C04D = 5,
  PPU_2C05A = 6,
  PPU_2C05B = 7,
  PPU_2C05C = 8,
  PPU_2C05D = 9,
  PPU_2C05E = 10
} NES_PPU_MODEL;

typedef enum {
  MIRROR_ONESCREEN_LOW,
  MIRROR_ONESCREEN_HIGH,
  MIRROR_VERTICAL,
  MIRROR_HORIZONTAL,
  MIRROR_FOUR_SCREENS,
} NES_MIRRORING_TYPE;

typedef enum {
  NTSC,
  PAL,
  DENDY,
  FAMICOM,
  VS_SYSTEM,
  PLAY_CHOISE,
  FDS,
  SYS_UNSPECIFIED
} NES_SYSTEM_TYPE;

typedef enum {
  VS_DEFAULT,
  RBIBASEBALL_PROTECTION,
  TKOBOXING_PROTECTION,
  SUPERXEVIOUS_PROTECTION,
  ICECLIMBER_PROTECTION,
  VS_DUAL_SYSTEM,
  RAIDONBUNGELINGBAY_PROTECTION
} NES_VS_SYSTEM_TYPE;

typedef enum {
  INP_UNSPECIFIED,
  STANDARDCONTROLLERS,
  FOURSCORE,
  FOURPLAYERADAPTER,
  VSSYSTEM,
  VSSYSTEMSWAPPED,
  VSSYSTEMSWAPAB,
  VSZAPPER,
  ZAPPER,
  TWOZAPPERS,
  BANDAIHYPERSHOT,
  POWERPADSIDEA,
  POWERPADSIDEB,
  FAMILYTRAINERSIDEA,
  FAMILYTRAINERSIDEB,
  ARKANOIDCONTROLLERNES,
  ARKANOIDCONTROLLERFAMICOM,
  DOUBLEARKANOIDCONTROLLER,
  KONAMIHYPERSHOT,
  PACHINKOCONTROLLER,
  EXCITINGBOXING,
  JISSENMAHJONG,
  PARTYTAP,
  OEKAKIDSTABLET,
  BARCODEBATTLER,
  MIRACLEPIANO,
  POKKUNMOGURAA,
  TOPRIDER,
  DOUBLEFISTED,
  FAMICOM3DSYSTEM,
  DOREMIKKOKEYBOARD,
  ROB,
  FAMICOMDATARECORDER,
  TURBOFILE,
  BATTLEBOX,
  FAMILYBASICKEYBOARD,
  PEC586KEYBOARD,
  BIT79KEYBOARD,
  SUBORKEYBOARD,
  SUBORKEYBOARDMOUSE1,
  SUBORKEYBOARDMOUSE2,
  SNESMOUSE,
  GENERICMULTICART,
  SNESCONTROLLERS,
  RACERMATEBICYCLE,
  UFORCE,
  LASTENTRY
} NES_INPUT_TYPE;

#endif // COMMON_TYPES_H